### PR TITLE
Persist slides in PDF

### LINKED ISSUE #9: Convert slides from speakers/community update into PDF
The current meetup artifacts collection depends on the slides link provided by speakers. This is external dependency. If links are gone, community members can no longer access the slides. We need to convert all slides into PDF and commited into this repo.

### PR DESCRIPTION
**Pull request by joshuabezaleel**
Fixes #9

### CODE REVIEW

**Comment by joshuabezaleel** [comment]
will change the link at the .yaml to the pdf slides in the next commit

**Comment by girikuncoro** [comment]
Great work on doing this @joshuabezaleel! This is critical to keep the materials accessible all the time by the community. Did you do this all manually?

**Comment by joshuabezaleel** [comment]
@girikuncoro yep, could not find an easier way to do this automatically

**Comment by girikuncoro** [comment]
@joshuabezaleel ok I think when we ask the slides from speakers, we should tell them to share in PDF instead, or ask them to raise PR for good engagement

**Pull request merged**
